# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/new/basys3_xdc.xdc

# IP: ip/disparity_ram/disparity_ram.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==disparity_ram || ORIG_REF_NAME==disparity_ram} -quiet] -quiet

# IP: ip/frame_buffer/frame_buffer.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==frame_buffer || ORIG_REF_NAME==frame_buffer} -quiet] -quiet

# IP: ip/Clocks/Clocks.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Clocks || ORIG_REF_NAME==Clocks} -quiet] -quiet

# XDC: ip/disparity_ram/disparity_ram_ooc.xdc

# XDC: ip/frame_buffer/frame_buffer_ooc.xdc

# XDC: ip/Clocks/Clocks_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==Clocks || ORIG_REF_NAME==Clocks} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: ip/Clocks/Clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==Clocks || ORIG_REF_NAME==Clocks} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: ip/Clocks/Clocks_ooc.xdc
